## Homework Week 2: CoCo 

### Task 1

In [27]:
#Define our first temperature
F = 30.3 #Farenheit

#Conversion
C = (5/9)*(F - 32) #Temp in Celcius

print(F, 'degrees Farenheit are equal to', round(C,3), 'degrees Celcius')

30.3 degrees Farenheit are equal to -0.944 degrees Celcius


### Task 2

In [28]:
#Import the numpy library
import numpy as np

#Define our array of temperatures
temperatures_F = np.array([30.3, 20.1, 46.5, 34.1, 42.3])

#Conversion from F to C
temperatures_C = (5/9)*(temperatures_F - 32)

print(np.round(temperatures_C,3))

[-0.944 -6.611  8.056  1.167  5.722]


### Task 3

In [29]:
import numpy as np

#Defining our array
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) #Need to reshape as a 4x4 matrix

In [30]:
#Show current shape of our array
np.shape(x)

(16,)

In [31]:
#Function used to reshape the array
x = np.reshape(x,(4,4))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
#Show the new shape of our array
np.shape(x)

(4, 4)

### Task 4

In [33]:
#Defining angles in degrees
deg = np.array([0,30,45,60,90])
print('Our angles in degrees are', deg)

#Convert degrees to radians
rad = np.radians(deg)
print('Our angles in radians are', np.round(rad,3))

Our angles in degrees are [ 0 30 45 60 90]
Our angles in radians are [0.    0.524 0.785 1.047 1.571]


In [34]:
#Calculate cosine and sine of these angles 
sin = np.sin(rad) 
cos = np.cos(rad) #These functions will read the angles in radians only

#Printing the results for each angle
i=0
while i < len(deg) :
 print('The sine and cosine of', deg[i], 'is', np.round(sin[i],3), 'and', np.round(cos[i],3), 'respectively')
 i = i+1
print('This loop is now over!')  

      

The sine and cosine of 0 is 0.0 and 1.0 respectively
The sine and cosine of 30 is 0.5 and 0.866 respectively
The sine and cosine of 45 is 0.707 and 0.707 respectively
The sine and cosine of 60 is 0.866 and 0.5 respectively
The sine and cosine of 90 is 1.0 and 0.0 respectively
This loop is now over!


### Task 5

In [2]:
#Finite difference approximation for discrete elements:
import numpy as np

#Defining our function y(x)
def y(a):
    y = a**2
    return y

#Entering what number we want to calculate y'=x^2 for
x = input("Enter what number we want y' to be calculated for: ")
x = int(x)

#Defining out spacing between values (h)
h = 0.00001

#Calculating the derivative as a finite difference approximation: 
derivative = (y(x+h)-y(x))/((x+h)-x)
print('The derivative of', x, 'is', round(derivative,))


Enter what number we want y' to be calculated for:  2


The derivative of 2 is 4


Another way of solving this exercise: 

In [19]:
#Finite difference approximation for discrete elements 2: 
import numpy as np

#Defining our function y(x)
def y(a):
    y = a**2 #For this example I just chose a simple quadratic function
    return y

#Creating a list of all the values within this function (we assume up until 100)
num = np.linspace(0,100,1001)

#Entering what number we want to calculate y'=x^2 for
x = input("Enter what number we want y' to be calculated for: ")
x = int(x)

#Finding this number in the array and selecting X(i+1)
i = 0
while i<10001:
    if num[i]==x: #if the ith number in my array is the one entered by user
        xii = num[i+1] #save the next number in the array as x(i+1) 
        xi = num[i]
        i = 10002 #set i higher than threshold to not come back into loop
    else:
        i=i+1
        
#Calculating the derivative as a finite difference approximation: 
derivative = (y(xii)-y(xi))/((xii)-xi)
print('The derivative of', x, 'is', round(derivative,))

Enter what number we want y' to be calculated for:  3


The derivative of 3 is 6.0


In [20]:
num

array([  0. ,   0.1,   0.2, ...,  99.8,  99.9, 100. ])

In [40]:
#Finite difference approximation for discrete elements 2: 
import numpy as np

#Defining our function y(x)
def y(a):
    y = a**2 #For this example I just chose a simple quadratic function
    return y

#Creating a list of all the values within this function (we assume up until 100)
num = np.linspace(0,50,10001)
        
#Calculating the derivative as a finite difference approximation: 
derivative = np.diff(y(num))/ np.diff(num)

print('La derivada de', num[400], 'es', round(derivative[400],2)) 
#Funciona con cualquier numero que quiera llamar de mi arreglo

La derivada de 2.0 es 4.0
